variables:
  database:
    user: sa
    password: strongpassword!
    url: jdbc:postgresql://host.docker.internal/course_online_test

spring:
  flyway:
    enabled: false
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true